services:
  - type: web
    name: pari
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: kunna
          property: connectionString
